version: '3.6'

services:
  postgres:
    image: postgres:11
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8091:8081"
  redis:
    image: redis:5-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 3
    command: redis-server --appendonly yes
  bullboard:
    image: deadly0/bull-board
    environment:
      REDIS_HOST: redis
    restart: on-failure
    ports:
      - "8071:3000"

volumes:
  postgres-data:
  redis-data:
