name: E2E test

on: [push]

jobs:
  e2e-test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: wnbaohW7mn
          POSTGRES_DB: authentication
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      maildev:
        image: maildev/maildev
        env:
          MAILDEV_INCOMING_USER: admin
          MAILDEV_INCOMING_PASS: wnbaohW7mn
        options: --health-cmd "wget -q -O- http://localhost/healthz || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
        - 1025:25
        - 1080:80
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: bahmutov/npm-install@v1
    - name: Run E2E tests
      run: |
        npm run typeorm migration:run
        npm run fixtures
        npm run test:e2e
      env:
        CI: 'true'
        PORT: 3000
        APP_SECRET: 444a45b38193572dd7d3c0d691d806b487dbdfe1
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: wnbaohW7mn
        POSTGRES_DB: authentication
        DATABASE_URL: postgres://admin:wnbaohW7mn@localhost:${{ job.services.postgres.ports[5432] }}/authentication
        ALLOWED_ORIGINS: '*'
        MAILGUN_SMTP_SERVER: localhost
        MAILGUN_SMTP_PORT: ${{ job.services.maildev.ports[25] }}
        MAILGUN_SMTP_LOGIN: admin
        MAILGUN_SMTP_PASSWORD: wnbaohW7mn
        MAILGUN_API_KEY: 6rtK845ev6ZSCD6NepoUcK727K266Yv8
        MAILGUN_DOMAIN: sandbox6rtK845ev6ZSCD6NepoUcK727K266Yv8.mailgun.org
        MAILGUN_PUBLIC_KEY: pubkey-6rtK845ev6ZSCD6NepoUcK727K266Yv8
        CLIENT_BASE_URL: http://localhost:3001
        PRODUCT_NAME: Nest.js Auth
        COMPANY_NAME: ACME Inc
        SMTP_SECURE: 'false'

  run-server:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: wnbaohW7mn
          POSTGRES_DB: authentication
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: bahmutov/npm-install@v1
    - name: Prepare the database
      run: |
        npm run typeorm migration:run
        npm run fixtures
        npm run fixtures
      env:
        PORT: 3000
        APP_SECRET: 444a45b38193572dd7d3c0d691d806b487dbdfe1
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: wnbaohW7mn
        POSTGRES_DB: authentication
        DATABASE_URL: postgres://admin:wnbaohW7mn@localhost:${{ job.services.postgres.ports[5432] }}/authentication
        ALLOWED_ORIGINS: '*'
        MAILGUN_SMTP_SERVER: ${{ secrets.MAILGUN_SMTP_SERVER }}
        MAILGUN_SMTP_PORT: ${{ secrets.MAILGUN_SMTP_PORT }}
        MAILGUN_SMTP_LOGIN: ${{ secrets.MAILGUN_SMTP_LOGIN }}
        MAILGUN_SMTP_PASSWORD: ${{ secrets.MAILGUN_SMTP_PASSWORD }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        MAILGUN_PUBLIC_KEY: ${{ secrets.MAILGUN_PUBLIC_KEY }}
        CLIENT_BASE_URL: http://localhost:3001
        PRODUCT_NAME: Nest.js Auth
        COMPANY_NAME: ACME Inc
        SMTP_SECURE: 'true'
    - name: Run the backend
      run: |
        npm run build
        npm start &
      env:
        PORT: 3000
        NODE_ENV: production
        APP_SECRET: 444a45b38193572dd7d3c0d691d806b487dbdfe1
        DATABASE_URL: postgres://admin:wnbaohW7mn@localhost:${{ job.services.postgres.ports[5432] }}/authentication
        ALLOWED_ORIGINS: '*'
        MAILGUN_SMTP_SERVER: localhost
        MAILGUN_SMTP_PORT: ${{ job.services.maildev.ports[1025] }}
        MAILGUN_SMTP_LOGIN: admin
        MAILGUN_SMTP_PASSWORD: wnbaohW7mn
        MAILGUN_API_KEY: 6rtK845ev6ZSCD6NepoUcK727K266Yv8
        MAILGUN_DOMAIN: sandbox6rtK845ev6ZSCD6NepoUcK727K266Yv8.mailgun.org
        MAILGUN_PUBLIC_KEY: pubkey-6rtK845ev6ZSCD6NepoUcK727K266Yv8
        CLIENT_BASE_URL: http://localhost:3001
        PRODUCT_NAME: Nest.js Auth
        COMPANY_NAME: ACME Inc
        SMTP_SECURE: 'false'
    - name: Run Postman collection
      run: npx newman run https://www.getpostman.com/collections/6b82b259fc751deda654
